/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AApp: typeof import('antdv-next')['App']
    AButton: typeof import('antdv-next')['Button']
    ACheckbox: typeof import('antdv-next')['Checkbox']
    AConfigProvider: typeof import('antdv-next')['ConfigProvider']
    ADivider: typeof import('antdv-next')['Divider']
    AFlex: typeof import('antdv-next')['Flex']
    AForm: typeof import('antdv-next')['Form']
    AFormItem: typeof import('antdv-next')['FormItem']
    AInput: typeof import('antdv-next')['Input']
    AInputPassword: typeof import('antdv-next')['InputPassword']
    ATypographyParagraph: typeof import('antdv-next')['TypographyParagraph']
    ATypographyText: typeof import('antdv-next')['TypographyText']
    ATypographyTitle: typeof import('antdv-next')['TypographyTitle']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

// For TSX support
declare global {
  const AApp: typeof import('antdv-next')['App']
  const AButton: typeof import('antdv-next')['Button']
  const ACheckbox: typeof import('antdv-next')['Checkbox']
  const AConfigProvider: typeof import('antdv-next')['ConfigProvider']
  const ADivider: typeof import('antdv-next')['Divider']
  const AFlex: typeof import('antdv-next')['Flex']
  const AForm: typeof import('antdv-next')['Form']
  const AFormItem: typeof import('antdv-next')['FormItem']
  const AInput: typeof import('antdv-next')['Input']
  const AInputPassword: typeof import('antdv-next')['InputPassword']
  const ATypographyParagraph: typeof import('antdv-next')['TypographyParagraph']
  const ATypographyText: typeof import('antdv-next')['TypographyText']
  const ATypographyTitle: typeof import('antdv-next')['TypographyTitle']
  const HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
}